### ISSUE TITLE
Day trajectories from point layer not working

### ISSUE THREAD

**Issue by no1rabbit** [movingpandas/qgis-processing-trajectory#16] opened 2021-03-16 12:36 UTC
Hi Anita,

I'm having a problem with creating daily trajectories.  
The error that comes up is:
ValueError: Trajectory dataframe must have at least two rows!
My points layer has a column for ID and timestamp and I have stipulated the timestamp format correctly according to my data.
I have managed to create the normal 'Trajectories from point layer' just not the day trajectories.
Any help will be most appreciated!! Thanks

**Comment by anitagraser** [comment] 2021-03-17 18:08
The cause for this error is most likely that there are one or more days with fewer than two records. This issue has been fixed (i.e. trajectories with fewer than two records are discarded) in MovingPandas but not yet in Trajectools.

**Comment by anitagraser** [comment] 2022-01-17 08:50
Will be fixed once #18 is implemented

**Closed** 2024-01-13 21:03 UTC
Labels: bug
